name: build-spread
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          CC=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          $CC -x c++ -std=c++11 -fno-exceptions -fno-rtti -fPIC -shared -O2 -o libspread.so spread.cpp
      - uses: actions/upload-artifact@v4
        with:
          name: libspread
          path: libspread.so
